repo_root <- normalizePath(file.path(testthat::test_path(), "..", "..", ".."), winslash = "/", mustWork = TRUE)
source(file.path(repo_root, "operator_hypothesis_lab", "R", "hyp_intraday_momentum_engine.R"))
source(file.path(repo_root, "operator_hypothesis_lab", "R", "hyp_reg_01_2_strategy_overlay.R"))
source(file.path(repo_root, "operator_hypothesis_lab", "R", "hyp_reg_09_1_robust_slope_fit_poc.R"))
source(file.path(repo_root, "operator_hypothesis_lab", "R", "hyp_reg_10_1_multi_horizon_agreement_poc.R"))

hreg101_test_bars <- function() { dates <- seq(as.Date("2020-01-02"), by = "day", length.out = 150L); close <- exp(cumsum(rep(.002, 150) + sin(seq_len(150)) * .001)); data.frame(symbol = "TEST", session_date = dates, timestamp_utc = as.POSIXct(dates, tz = "UTC"), open = close, high = close * 1.01, low = close * .99, close = close, volume = 1000) }
hreg101_frame <- function() { x <- hreg12_cross_frame(hreg101_test_bars()); x$normalized_return20 <- 1; x$normalized_return60 <- 1; x$normalized_return120 <- 1; x$sign20 <- 1; x$sign60 <- 1; x$sign120 <- 1; x$agreement_score <- 1; x$agreement_fraction <- 1; x$agreement_state <- "FULL_UP"; x$transition_event <- "NONE"; x$full_up_eligible <- TRUE; x }

testthat::test_that("contract freezes one 20/60/120 agreement lane", { x <- hreg101_contract(); testthat::expect_equal(x$hypothesis_id, "HYP-REG-10.1"); testthat::expect_equal(x$horizons, c(20L, 60L, 120L)); testthat::expect_equal(x$policies, c("UNFILTERED", "ENTRY_FULL_UP_ONLY")); testthat::expect_equal(x$confirmation_start, as.Date("2024-01-02")) })
testthat::test_that("normalized returns preserve sign and price-scale invariance", { up <- .002 * seq_len(121) + sin(seq_len(121)) * .0002; a <- hreg101_normalized_return(up); b <- hreg101_normalized_return(-up); c <- hreg101_normalized_return(up + log(7)); testthat::expect_gt(a[["normalized_return"]], 0); testthat::expect_lt(b[["normalized_return"]], 0); testthat::expect_equal(a[["normalized_return"]], c[["normalized_return"]], tolerance = 1e-12) })
testthat::test_that("rolling horizon starts only after h completed returns", { close <- exp(cumsum(rep(.001, 130) + sin(seq_len(130)) * .0001)); x <- hreg101_rolling_horizon(close, 20); testthat::expect_true(all(is.na(x$normalized_return[1:20]))); testthat::expect_true(all(is.finite(x$normalized_return[21:130]))) })
testthat::test_that("all five agreement states classify exactly", { testthat::expect_equal(hreg101_classify(c(1,-1,-1,1,1), c(1,-1,1,-1,1), c(1,-1,1,-1,-1)), c("FULL_UP","FULL_DOWN","SHORT_OPPOSES_UP","SHORT_OPPOSES_DOWN","MIXED")) })
testthat::test_that("join events require a stable long context and prior opposition", { state <- c("SHORT_OPPOSES_UP","FULL_UP","FULL_UP","SHORT_OPPOSES_DOWN","FULL_DOWN"); s60 <- c(1,1,1,-1,-1); s120 <- s60; testthat::expect_equal(hreg101_transition_event(state,s60,s120), c("NONE","SHORT_JOINS_UP","NONE","NONE","SHORT_JOINS_DOWN")) })
testthat::test_that("synthetic paths hit their intended states", { c <- hreg101_contract(); c$synthetic_paths <- 30L; s <- hreg101_synthetic_summary(hreg101_synthetic_calibration(c)); intended <- s[!is.na(s$target_state), ]; testthat::expect_true(all(intended$target_state_fraction >= .95)) })
testthat::test_that("scale and append invariance are exact", { testthat::expect_lte(max(hreg101_scale_invariance_audit()$absolute_difference), 1e-12); testthat::expect_true(all(hreg101_causality_audit()$passed)) })
testthat::test_that("ledger full-up eligibility matches state exactly", { c <- hreg101_contract(); bars <- hreg101_test_bars(); x <- hreg101_build_asset_ledger(bars,c); testthat::expect_true(all(x$full_up_eligible %in% c(TRUE,FALSE,NA))); testthat::expect_true(all(x$agreement_state[x$full_up_eligible %in% TRUE] == "FULL_UP")) })
testthat::test_that("confirmation and duplicate rows are rejected", { bars <- hreg101_test_bars(); bars$session_date <- seq(as.Date("2023-11-01"), by="day", length.out=nrow(bars)); testthat::expect_error(hreg91_assert_bars(bars,hreg101_contract()),"Confirmation"); bars <- hreg101_test_bars(); testthat::expect_error(hreg91_assert_bars(rbind(bars,bars[1,]),hreg101_contract()),"duplicated") })
testthat::test_that("entry policy skips rejected crosses rather than deferring", { frame <- hreg101_frame(); cross <- which(frame$cross_up)[1L]; frame$full_up_eligible[[cross]] <- FALSE; schedule <- hreg101_schedule(frame,min(frame$session_date),max(frame$session_date),"ENTRY_FULL_UP_ONLY"); testthat::expect_true(schedule$blocked_entry[[cross+1L]]); testthat::expect_false(schedule$target[[cross+1L]]); testthat::expect_false(any(schedule$entry_signal[seq.int(cross+2L,min(cross+4L,nrow(schedule)))])) })
testthat::test_that("unfiltered and fully eligible schedules agree", { frame <- hreg101_frame(); a <- hreg101_schedule(frame,min(frame$session_date),max(frame$session_date),"UNFILTERED"); b <- hreg101_schedule(frame,min(frame$session_date),max(frame$session_date),"ENTRY_FULL_UP_ONLY"); testthat::expect_equal(a$target,b$target) })
testthat::test_that("circular controls are deterministic and nonzero", { frame <- hreg101_frame(); a <- hreg101_shifted_schedule(frame,min(frame$session_date),max(frame$session_date),7); b <- hreg101_shifted_schedule(frame,min(frame$session_date),max(frame$session_date),7); testthat::expect_equal(a$target,b$target); testthat::expect_gt(attr(a,"shift_offset"),0) })
testthat::test_that("exposure-nearest selection ignores returns", { x <- data.frame(simulation_id=1:4,median_exposure=c(.1,.2,.3,.4),median_return=c(100,-100,50,0)); testthat::expect_equal(hreg101_exposure_near_ids(x,.26,2),c(3L,2L)) })
