options(stringsAsFactors = FALSE)

script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
if (length(script_arg) != 1L) stop("Expected exactly one --file argument.", call. = FALSE)
script_path <- normalizePath(sub("^--file=", "", script_arg), winslash = "/", mustWork = TRUE)
repo_root <- normalizePath(file.path(dirname(script_path), "..", ".."), winslash = "/", mustWork = TRUE)

source(file.path(repo_root, "scripts", "lib", "repo_local_libs.R"))
g5_use_repo_local_libs(repo_root)
source(file.path(repo_root, "R", "config_loader.R"))
source(file.path(repo_root, "operator_hypothesis_lab", "R", "hyp_alt_01_1_reddit_attention.R"))
g5_load_local_renviron(repo_root)

config <- ha011_config_from_env(repo_root)
key_id <- ha011_env_or_object("ALPACA_KEY", c("ALPACA_KEY", "ALPACA_KEY_ID"))
secret_key <- ha011_env_or_object("ALPACA_SECRET", c("ALPACA_SECRET", "ALPACA_SECRET_KEY"))
trading_base_url <- Sys.getenv("ALPACA_TRADING_BASE_URL", unset = "https://paper-api.alpaca.markets")
registry <- ha011_alpaca_registry(key_id, secret_key, base_url = trading_base_url)
ha011_atomic_write_csv(registry, config$ticker_registry_path)
cat("Registry status: PASS\n")
cat("Active US-equity/ETF symbols:", nrow(registry), "\n")
cat("Registry path:", normalizePath(config$ticker_registry_path, winslash = "/", mustWork = TRUE), "\n")
